name: Release

on:
  push:
    branches: [ main ]
    tags: [ 'v*.*.*' ]

env:
  commit_msg: ${{ github.event.head_commit.message }}


jobs:
  release:
    runs-on: ubuntu-latest

    permissions:
      packages: write
      contents: write

    steps:
      - name: Setup yq
        run: sudo snap install yq

      - name: Install yarn dependencies
        uses: DerYeger/yarn-setup-action@master
        with:
          node-version: 22
      - name: Build html
        run: ./bin/compile-html
      - name: Archive html
        run: zip -r html.zip build/*
      - name: Release project
        id: create_release
        uses: CupOfTea696/gh-action-auto-release@v1.0.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Upload build to release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./html.zip
          asset_name: html.zip
          asset_content_type: application/zip
